import Image from "next/image";
import privacyPolicies from "@/data/privacy";
import TableOfContent from "@/components/ui/TableOfContent";

export const metadata = {
  title: "Aeroforge | Privacy Policy",
  description: "Generated by create next app",
};

const PrivacyPolicy = () => {
  return (
    <>
      <header className=" w-full bg-header py-4 lg:py-5 px-6 xl:px-10">
        <div className="h-8 xs:h-10 lg:h-12 relative">
          <Image
            src={"/aeroforge-logo-light.svg"}
            alt="logo"
            fill
            priority={true}
          />
        </div>
      </header>
      <main className="px-6 xl:px-10">
        <h1 className="font-bold text-black text-3xl xs:text-4xl lg:text-5xl my-8 xs:my-12 lg:my-16 text-center">
          Privacy Policy
        </h1>
        <div className="flex flex-col md:flex-row gap-6 justify-center">
          <div className="">
            <TableOfContent list={privacyPolicies} />
          </div>
          <section className="max-w-[920px] flex flex-col gap-y-6 lg:gap-y-7">
            {privacyPolicies.map(({ title, description }, i) => {
              return (
                <article
                  className="lg:text-lg text-primary"
                  key={i}
                  id={title.replaceAll(" ", "-")}
                >
                  <h2 className="font-bold">{`${i + 1}. ${title}`}</h2>
                  <p className="leading-normal whitespace-pre-wrap">
                    {description}
                  </p>
                </article>
              );
            })}
            <div className="lg:-mt-1 flex flex-col gap-y-6">
              <hr className="border-t border-[#D6D6D9]" />
              <p className="text-base lg:text-lg leading-normal text-black">
                <strong>Updated:</strong> 28<sup>th</sup> November,2024
              </p>
            </div>
          </section>
        </div>
      </main>
      <footer className="text-black text-center text-base lg:text-lg py-10 px-6 xl:px-10">
        &copy; AEROFORCE LTD is a registered company 1234567890. All Rights
        Reserved.
      </footer>
    </>
  );
};

export default PrivacyPolicy;
